#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 250

#define COMBO_TERM 60

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 18

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 10

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "zrn9d/6awNon"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 11

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

